### ISSUE TITLE
[0.1.0] Separate folders for ORM/ODM classes

### ISSUE THREAD

**Issue by Edwin-Luijten** [Jiro-Commerce/Product#3]
Would it be better for organization sake to put ORM/ODM classes in a separate folder?
For example: Src/Eloquent/Product.php or: Src/Database/Eloquent/Product.php

**Comment by andrewmclagan** [comment]
I have considered this approach. Currently still very flexible on the folder structure / namespacing. I can see the advantages of separating the drivers out if there are any future ORM/ODM alternate implementations. 

Will defiantly think more on this before bumping the version... The `Src/Eloquent/Product.php` structure appeals to me most. What do you think?

**Comment by ThatTomPerson** [comment]
I think `src/Database/Eloquent/Product.php` is better then `src/Eloquent/Product.php`

who knows what other connectors people might want to add later
`Jiro\Product\Database\Eloquent\Product`,
`Jiro\Product\Database\Kohana\Product`,
`Jiro\Product\Database\Mongo\Product`,
`Jiro\Product\Database\Cassandra\Product`
etc

But I don't know, that is just how I like my projects

**Comment by andrewmclagan** [comment]
The reason I lean more towards the `Src/Eloquent/Product.php` structure is I like to group domain objects together, although I'm open to any approach really. I'd prefer to do whats most common...

**Comment by andrewmclagan** [comment]
Im working on something now... I think it will be tighter. 
* Splitting out Properties & Variations into separate packages
* Refactoring namespaces
* Repo clean up

Let me know what you think... thanks guys

next move will be: Builders / Factories to easily create product / option / variation combinations...

**Comment by Edwin-Luijten** [comment]
I like the proposals, about the name-spacing for ORM stuff, I dont have a preferred name on src/Database/etc... and src/Eloquent/etc..

Splitting out those other components will make management easier. I think I went a-head and have copied the code and splitted them out already. Can I mail a zip to you @andrewmclagan ? Then you can review/update etc.

**Comment by andrewmclagan** [comment]
@Edwin-Luijten thanks! Although im some way along with some other namespacing changes. There will have to be a few structural changes as well. I will be making the Property & Variation stand alone packages. That will give those abilities to any model...

**Comment by andrewmclagan** [comment]
create a pull request i would still love to see what you have done (Y)

**Comment by andrewmclagan** [comment]
As per the discussion in (this pull req.)[https://github.com/Jiro-Commerce/Product/pull/4] drivers will now be living in the following structure `..\Database\Eloquent\..`

**Comment by andrewmclagan** [comment]
Take a look over where it is at now, see what you think. Have not run the tests yet, still rough. tagging this as 0.1.0.

**Comment by Edwin-Luijten** [comment]
I'm liking it =), The location of the interfaces is flexible to, if you placed them in the Database folder you would lose flexibility. This way you can use them for different kind of persistence layers, like XML, json etc.

Have you tought of a way how a developer could switch between ORMs?
I made a quick draft of the builder:
```php
<?php namespace Jiro\Product\Builder;

use Jiro\Product\RepositoryInterface as ProductRepository;
use Jiro\Property\RepositoryInterface as PropertyRepository;

class ProductBuilder implements ProductBuilderInterface {

	/**
     * Currently built product.
     *
     * @var ProductInterface
     */
    protected $product;
	
	/**
     * Product repository.
     *
     * @var ProductRepositoryInterface
     */
    protected $productRepository;

    /**
     * Property repository.
     *
     * @var PropertyInterface
     */
    protected $propertyRepository;

	public function __construct(ProductRepository $productRepository, PropertyRepository $propertyRepository)
	{
		$this->productRepository = $productRepository;
        $this->propertyRepository = $propertyRepository;
	}
	
	/**
     * {@inheritdoc}
     */
    public function __call($method, $arguments)
    {
        if (!method_exists($this->product, $method)) {
            throw new \BadMethodCallException(sprintf('Product has no "%s()" method.', $method));
        }

        call_user_func_array([$this->product, $method], $arguments);

        return $this;
    }
	
	/**
     * {@inheritdoc}
     */
    public function create($name)
    {
        $this->product = $this->productRepository->createNew();
        $this->product->setName($name);

        return $this;
    }
	
	/**
     * {@inheritdoc}
     */
	public function addProperty($name, $value, $presentation = null)
    {
        $property = $this->propertyRepository->findByName($name);

        if($property === null)
        {
            $property = $this->propertyRepository->createNew();
            $property->setName($name);
            $property->setValue($value);
            $property->setPresentation($presentation);

            $this->product->addProperty($property);
        }

        return $this;
    }
	
	/**
     * {@inheritdoc}
     */
    public function save()
    {
        $this->productRepository->save($this->product);

        return $this->product;
    }
}
```

**Comment by andrewmclagan** [comment]
Look fantastic. Mind creating a pull request? :-)
